{{- if include "lumovi.dashboard" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumovi.fullname" . }}
  labels:
    {{- include "lumovi.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "lumovi.selectorLabels" . | nindent 4 }}
{{- end }}
