import {
  Activity,
  Archive,
  Box,
  CalendarClock,
  Copy,
  Cpu,
  Database,
  FileCode2,
  Gauge,
  Globe,
  HardDrive,
  KeyRound,
  Layers,
  LayoutGrid,
  Network,
  Play,
  Server,
  ShieldCheck,
  SquareStack,
  type LucideIcon,
} from 'lucide-react'
import type { ResourceKind } from '@shared/resources'

export const KIND_ICONS: Record<ResourceKind, LucideIcon> = {
  Node: Server,
  Namespace: LayoutGrid,
  Event: Activity,
  Pod: Box,
  Deployment: Layers,
  StatefulSet: Database,
  DaemonSet: Cpu,
  ReplicaSet: Copy,
  Job: Play,
  CronJob: CalendarClock,
  HorizontalPodAutoscaler: Gauge,
  Service: Network,
  Ingress: Globe,
  NetworkPolicy: ShieldCheck,
  ConfigMap: FileCode2,
  Secret: KeyRound,
  PersistentVolumeClaim: HardDrive,
  PersistentVolume: SquareStack,
  StorageClass: Archive,
}
