{{- if and (eq .Values.auth.mode "oidc") .Values.auth.oidc.clientSecret (not .Values.auth.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubestacks.fullname" . }}-oidc
  labels:
    {{- include "kubestacks.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.auth.oidc.clientSecret | b64enc | quote }}
{{- end }}
